<?php

namespace parking\parkingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AttenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttenteRepository extends EntityRepository
{
}
