parameters:
#    parkingparking.example.class: parking\parkingBundle\Example

services:
#    parkingparking.example:
#        class: %parkingparking.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
